name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true       # continue-on-error on job level
    strategy:
      matrix:                     # run the same job with different configurations
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:                 # include single combination
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:                  # exclude single combination      
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build